version: '3'

services: 

  app:
    build:
      dockerfile: ./node/Dockerfile
    container_name: app
    networks: 
      - node-network
    volumes: 
      - ./node:/usr/src/app
    tty: true
    depends_on:
      db:
        condition: service_healthy
        
  db:
    image: mysql:8.0
    container_name: database
    restart: always
    tty: true
    volumes: 
      - ./database:/docker-entrypoint-initdb.d
    command: --innodb-use-native-aio=0
    environment: 
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "nodedb"
      MYSQL_INIT_CONNECT: 'SET GLOBAL allow_public_key_retrieval = 1;'
      MYSQL_ALLOW_EMPTY_PASSWORD: false
    networks: 
      - node-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 20s
      timeout: 30s
      retries: 3


  nginx:
    build: 
     dockerfile: ./nginx/Dockerfile
    networks:
      - node-network
    volumes:
      - ./nginx:/usr/share/nginx/html:rw
    tty: true
    ports:
      - 8080:80
    depends_on:
      - app
  

networks: 
  node-network:
    driver: bridge

volumes:
  database:
  postgres_data: